// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omowxmgpxkdsfbefudwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tb3d4bWdweGtkc2ZiZWZ1ZHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyOTgxMjQsImV4cCI6MjA3Nzg3NDEyNH0.Ydsw4wwVmjg80On_weiym6Kj7Qp85ykCtx6LtJyhW4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});